let arr = getArray();
console.log('--- get last element ---');
console.log('arr.at(-1)) = ' + arr.at(-1));
console.log('arr.at(-2)) = ' + arr.at(-2));
console.log('--- delete last element ---');
console.log('arr.pop() = ' + arr.pop());
console.log('arr = ' + arr);
console.log('arr.pop() = ' + arr.pop());
console.log('arr = ' + arr);
console.log('--- add last element ---');
console.log('arr.push("9") = ' + arr.push("8"));
console.log('arr = ' + arr);
console.log('arr.push("9") = ' + arr.push("9"));
console.log('arr = ' + arr);
console.log('--- delete first element ---');
console.log('arr.shift() = ' + arr.shift());
console.log('arr = ' + arr);
console.log('arr.shift() = ' + arr.shift());
console.log('arr = ' + arr);
console.log('--- add first element ---');
console.log('arr.unshift("1") = ' + arr.unshift("1"));
console.log('arr = ' + arr);
console.log('arr.unshift("0") = ' + arr.unshift("0"));
console.log('arr = ' + arr);
console.log('--- delete and add element ---');
console.log('arr.splice(2, 1, "0",  "0",  "0") = ' + arr.splice(2, 1, "0",  "0",  "0"));
console.log('arr = ' + arr);
console.log('arr.splice(6, 5, "0",  "0",  "0") = ' + arr.splice(6, 5, "0",  "0",  "0"));
console.log('arr = ' + arr);
console.log('arr.splice(-1, 0, "0",  "0",  "0") = ' + arr.splice(-1, 0, "0",  "0",  "0"));
console.log('arr = ' + arr);
console.log('--- copy elements ---');
arr = getArray();
console.log('arr.slice(1, 3) = ' + arr.slice(1, 3));
console.log('arr.slice(1) = ' + arr.slice(1));
console.log('arr.slice(-2) = ' + arr.slice(-2));
console.log('arr.slice(-3, -1) = ' + arr.slice(-3, -1));
console.log('arr.slice(-4, 10) = ' + arr.slice(-4, 10));
console.log('arr.slice() = ' + arr.slice());
console.log('--- combining arrays ---');
let arr1 = ["0", "1", "2"];
let arr2 = ["3", "4", "5"];
let arr3 = ["6", "7", "8"];
console.log('arr1 = ' + arr1);
console.log('arr2 = ' + arr2);
console.log('arr3 = ' + arr3);
console.log('arr1.concat(arr2, arr3, "9") = ' + arr1.concat(arr2, arr3, "9"));
console.log('arr1 = ' + arr1);
console.log('arr2 = ' + arr2);
console.log('arr3 = ' + arr3);
console.log('---------------------------------');

function getArray() {
    let arr = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9",];
    console.log('arr = ' + arr);
    return arr;
}